### ISSUE TITLE
Syntax coloring in DrRacket

### ISSUE THREAD

**Issue by Metaxal** [lathe/parendown-for-racket#1]
I'm finally trying out Parendown, it's pretty neat! I might adopt it eventually, but...

do you know if there's a way to make DrRacket not shout in red when using Parendown?

![Screenshot from 2020-12-09 10-58-58](https://user-images.githubusercontent.com/1658140/101621363-91cc4000-3a0d-11eb-8c86-18c616b80dc3.png)

**Comment by rocketnia** [comment]
Wow, lol, I'm sorry, and thanks for the report!

I thought I had tried it with DrRacket, but maybe not, because I don't remember seeing that red highlighting. Fixing this would probably involve... well, getting to know the `#lang` system well enough to customize the syntax highlighting rather than just the reader.

**Comment by rocketnia** [comment]
Hopefully it's not shouting now. Can you check this @Metaxal?

It'd be nice to have an indenter too. I'm honestly not sure what an ideal DrRacket indenter for Parendown would be like, but there's room for improvement anyway. This probably deserves its own dedicated issue.

**Comment by rocketnia** [comment]
I'm going to close this issue now, but thanks for reporting this, and if you still encounter issues, please feel free to report those as well.

**Comment by Metaxal** [comment]
Sorry, I forgot about. Yes, it works, thanks a bunch!

**Comment by rocketnia** [comment]
Oh, great to hear. :)
